site_name: Chart_Builder
theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            merge_init_into_namespace: true
            show_signature: true
            show_signature_annotations: true

nav:
  - SDK Reference:
      - Chart_Builder: sdk_reference.md
